[package]
	name = "report_generator"
	version = "0.1.0"
	authors = ["Don Allen <donaldcallen@gmail.com>"]

[dependencies]
	rust_library={path="../rust_library"}
	libc = "0.2.60"
    time = "0.1.42"
	[dependencies.rusqlite]
		version = "0.20.0"
		features = ["load_extension"]


