#!/usr/bin/dash

if test $# -ne 2
then
    echo 'Usage: newcashAMEXImporter <amex csv file> <newcash database>'
    exit 1
else
    SYSTEM=`uname`
    awk -F , '
    $1 == "Date" {next} 
    {printf "%s,%s,%s\n", $1, $3, $6}' $1 | sort | newcashLoadTransactions.tcl ${HOME}/lib/${SYSTEM}/levenshtein.so $2
fi
