#!/usr/bin/dash

# Get the directory where this script lives, because that's where the .awk files also live
dir=`dirname $0`

if test $# != 1
then
    echo 'Usage: newcashVangardPreProcess pathToVanguardCSVFile'
    exit 1
else    
    awk -f ${dir}/newcashVanguardPreProcessCSV.awk $1 | sort -t ',' -k 1
fi
